name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and upload release asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          cd custom_components/ship24
          zip -r ../../ship24.zip .

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: ship24.zip
